id: AD7BDAB19
title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven-Line Prayer'
type: translation
pechas:
- IFB3D64DC
- I7049F51F
- IEA992BFB
- IBAB98664
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:08:26.090783
  last_modified_at: 2023-01-04 13:08:26.090787
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IFB3D64DC/8E18: C1FC
  I7049F51F/E333: C1FC
  IEA992BFB/F04F: C1FC
  IBAB98664/6E36: C1FC
